version: '3'

services:
  web:
    image: tchaudhry/nginx-certbot-docker
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=tux-sudo.com
      - EMAIL=tanmay.chaudhry@gmail.com
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./config/nginx_config.conf:/etc/nginx/conf.d/default.conf

volumes:
  letsencrypt:
