version: '3'

services:
  web:
    image: abiosoft/caddy 
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDYPATH=/etc/caddycerts 
    volumes:
      - $HOME/.caddy:/etc/caddycerts
      - ./config/caddyfile:/etc/Caddyfile
