---

- name: Create App directory
  file:
    path: /var/lib/tux-sudo
    state: directory
    mode: 0755

- name: Add stack config to instance
  copy:
    src: files/docker-compose.yml
    dest: /var/lib/tux-sudo/docker-compose.yml
    owner: tux_sudo 
    mode: 0644

- name: Add config files
  copy:
    src: files/config
    dest: /var/lib/tux-sudo

- name: Docker Compose Pull Images
  command: docker-compose pull --quiet web
  async: 1800
  poll: 5
  args:
    chdir: /var/lib/tux-sudo

- name: Bring Up Docker Services
  command: docker-compose up -d --force-recreate
  async: 1800
  poll: 5
  args:
    chdir: /var/lib/tux-sudo

- name: Certify
  command: docker exec web /certify.sh
