---

- name: Get APT-Key
  apt_key:
    url: "https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub"
    state: present

- name: Add APT-Repo
  apt_repository:
    repo: "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main"
    state: present

- name: APT-update
  apt:
    update_cache: yes

- name: UnInstall Salt
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - salt-master
    - salt-minion
    - salt-ssh
    - salt-syndic
    - salt-cloud
    - salt-api

- name:  Disable Salt and Start
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - salt-master
    - salt-minion
    - salt-ssh
    - salt-syndic
    - salt-cloud
    - salt-api
