---

- name: Get APT-Key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add APT-Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present

- name: APT-update
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: latest

- name: Enable Docker Daemon
  systemd:
    name: docker
    enabled: yes

- name: Install docker-compose
  pip:
    name: docker-compose
